import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: '--font-poppins',
  weight: ["400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Jaja ID | Company Profile ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
